#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-Misty1
version:      1.1.1
version_from: Misty1.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
